### ISSUE TITLE
ToDo plugin throws a JS error every so often when it is enabled

### ISSUE THREAD

**Issue by DHaussermann** [mattermost-community/mattermost-plugin-todo#130]
When ever the plugin the ToDo plugin isa enabled I see a JSA error show in the dev console every so often. This occurs within about a minute of having the plugin enabled regardless of if the user touches the functionality. 
This occurs on version `v0.4.0`. I can't find any functional implications when the error occurs.

Steps:
- Install and enable the plugin 
- Open any channel
- Open the dev console
- Wait a minute or 2
**Observed**
![Screen Shot 2020-12-21 at 11 52 18 AM](https://user-images.githubusercontent.com/35588783/102811693-c0460580-4393-11eb-8c78-3fcf86d8c62d.png)
Error seems to occur here: `https://<server url>/static/plugins/com.mattermost.plugin-todo/com.mattermost.plugin-todo_dc5f2cee49573681_bundle.js`

0.4.0

**Comment by catalintomai** [comment]
@DHaussermann , is this still repro-ing, after the latest ToDo release(s)? Maybe we can close this.

**Comment by catalintomai** [comment]
@DHaussermann , assigning this back to you for closing.

**Comment by AayushChaudhary0001** [comment]
@ayusht2810 @DHaussermann This issue is not reproducible now on master branch.
