### ISSUE TITLE
TODO add message preview Functionality issue. 

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost-community/mattermost-plugin-todo#168]
issue 1 :- in the preview, text Should not visible in the one line.
issue 2 :- that text written in the left side so in the preview its should visible in the left side but currently in the preview its visible in the right side.

video :- 
https://user-images.githubusercontent.com/89907719/166416425-3bbdbab7-6ca8-4b70-ba8a-f55c3d44e8ce.mov

**Comment by AayushChaudhary0001** [comment]
@dipak-demansol @ayusht2810 This issue is not reproducible on master branch now.
