### ISSUE TITLE
Adding a ToDo does not work when using "Add to Thread" option 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost-community/mattermost-plugin-todo#175]
When a user creates a ToDo from a post in Mattermost AND checks the option for "Add to thread" a JS error occurs and the save is non functional.
![image](https://user-images.githubusercontent.com/35588783/186471233-ef1a56f1-1c91-40ad-b8fa-eae0eb18de73.png)
I also see a message regarding username. 
`[Util] handleError::  Uncaught TypeError: Cannot read properties of null (reading 'username'`)
 Note this happens regardless of weather or not the ToDo is assigned to anyone.

Steps:
- Deploy a build that include the UX overhaul (Can use `master`) 
- Make a post
- Click the action to add a ToDo
- Check the box to add the post to the thread
- Click Save
**Observed**: JS error occurred and save has failed.

**Comment by DHaussermann** [comment]
@asaadmahmood This seems like it occurs only after the UX changes. Let me know if you're able to take a look.

**Comment by AayushChaudhary0001** [comment]
@DHaussermann I tried to test and reproduce the above issue but i was not able to do so.

Steps that were followed:-
- Deployed a build from the master branch
- Created a post in channel
- From the action menu, added a todo of the same post.
- Checked the add to thread checkbox and saved.

The ToDo got saved and was reflecting in RHS.
cc: @ayusht2810
